// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Joplin"),
      "slug", v_str("joplin"),
      "version", v_str("0.0.1"),
      "target", v_str("c")),
    "feature", cmap(8,
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("http://localhost:41184"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(3,
        "folder", v_map(),
        "note", v_map(),
        "tag", v_map()),
      "auth", cmap(3,
        "prefix", v_str(""),
        "in", v_str("query"),
        "name", v_str("token"))),
    "entity", cmap(3,
      "folder", cmap(5,
        "fields", clist(8,
          cmap(4,
            "name", v_str("created_time"),
            "title", v_str("Created Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the folder was created.")),
          cmap(3,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("is_shared"),
            "title", v_str("Is Shared"),
            "type", v_str("`$INTEGER`")),
          cmap(4,
            "name", v_str("parent_id"),
            "title", v_str("Parent Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("ID of the parent notebook, empty for a top-level notebook.")),
          cmap(4,
            "name", v_str("title"),
            "title", v_str("Title"),
            "type", v_str("`$STRING`"),
            "short", v_str("The folder title.")),
          cmap(4,
            "name", v_str("updated_time"),
            "title", v_str("Updated Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the folder was last updated.")),
          cmap(4,
            "name", v_str("user_created_time"),
            "title", v_str("User Created Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the folder was created.")),
          cmap(4,
            "name", v_str("user_updated_time"),
            "title", v_str("User Updated Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the folder was last updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("folder"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/folders"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("folders"))),
                "parts", clist(1,
                  v_str("folders")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", v_map(),
                "select", v_map()))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(2,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/folders"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("folders"))),
                "parts", clist(1,
                  v_str("folders")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.items`")),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("order_by"),
                      "orig", v_str("order_by"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("order_dir"),
                      "orig", v_str("order_dir"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("page"),
                      "orig", v_str("page"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(1)))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("field"),
                    v_str("order_by"),
                    v_str("order_dir"),
                    v_str("page")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/folders/{id}/notes"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("folders")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("notes"))),
                "parts", clist(3,
                  v_str("folders"),
                  v_str("{id}"),
                  v_str("notes")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.items`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(2,
                  "$action", v_str("note"),
                  "exist", clist(2,
                    v_str("field"),
                    v_str("id")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/folders/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("folders")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("folders"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("field"),
                    v_str("id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/folders/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("folders")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("folders"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/folders/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("folders")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("folders"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "note", cmap(5,
        "fields", clist(18,
          cmap(3,
            "name", v_str("altitude"),
            "title", v_str("Altitude"),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("author"),
            "title", v_str("Author"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("body"),
            "title", v_str("Body"),
            "type", v_str("`$STRING`"),
            "short", v_str("The note body, in Markdown.")),
          cmap(4,
            "name", v_str("created_time"),
            "title", v_str("Created Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the note was created.")),
          cmap(3,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("is_conflict"),
            "title", v_str("Is Conflict"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Tells whether the note is a conflict or not.")),
          cmap(4,
            "name", v_str("is_todo"),
            "title", v_str("Is Todo"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("Tells whether this note is a to-do or not.")),
          cmap(3,
            "name", v_str("latitude"),
            "title", v_str("Latitude"),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("longitude"),
            "title", v_str("Longitude"),
            "type", v_str("`$NUMBER`")),
          cmap(4,
            "name", v_str("markup_language"),
            "title", v_str("Markup Language"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("1 for Markdown, 2 for HTML.")),
          cmap(4,
            "name", v_str("parent_id"),
            "title", v_str("Parent Id"),
            "type", v_str("`$STRING`"),
            "short", v_str("ID of the notebook that contains this note.")),
          cmap(4,
            "name", v_str("source_url"),
            "title", v_str("Source Url"),
            "type", v_str("`$STRING`"),
            "short", v_str("The full URL where the note comes from.")),
          cmap(4,
            "name", v_str("title"),
            "title", v_str("Title"),
            "type", v_str("`$STRING`"),
            "short", v_str("The note title.")),
          cmap(4,
            "name", v_str("todo_completed"),
            "title", v_str("Todo Completed"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the to-do was completed.")),
          cmap(4,
            "name", v_str("todo_due"),
            "title", v_str("Todo Due"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the to-do is due.")),
          cmap(4,
            "name", v_str("updated_time"),
            "title", v_str("Updated Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the note was last updated.")),
          cmap(4,
            "name", v_str("user_created_time"),
            "title", v_str("User Created Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the note was created.")),
          cmap(4,
            "name", v_str("user_updated_time"),
            "title", v_str("User Updated Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the note was last updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("note"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/notes"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("notes"))),
                "parts", clist(1,
                  v_str("notes")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", v_map(),
                "select", v_map()))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(2,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/notes"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("notes"))),
                "parts", clist(1,
                  v_str("notes")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.items`")),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("order_by"),
                      "orig", v_str("order_by"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("order_dir"),
                      "orig", v_str("order_dir"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("page"),
                      "orig", v_str("page"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(1)))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("field"),
                    v_str("order_by"),
                    v_str("order_dir"),
                    v_str("page")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/notes/{id}/tags"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("notes")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("tags"))),
                "parts", clist(3,
                  v_str("notes"),
                  v_str("{id}"),
                  v_str("tags")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.items`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(2,
                  "$action", v_str("tag"),
                  "exist", clist(2,
                    v_str("field"),
                    v_str("id")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/notes/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("notes")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("notes"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("field"),
                    v_str("id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/notes/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("notes")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("notes"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/notes/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("notes")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("notes"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "tag", cmap(5,
        "fields", clist(6,
          cmap(4,
            "name", v_str("created_time"),
            "title", v_str("Created Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the tag was created.")),
          cmap(3,
            "name", v_str("id"),
            "title", v_str("Id"),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("title"),
            "title", v_str("Title"),
            "type", v_str("`$STRING`"),
            "short", v_str("The tag title.")),
          cmap(4,
            "name", v_str("updated_time"),
            "title", v_str("Updated Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the tag was last updated.")),
          cmap(4,
            "name", v_str("user_created_time"),
            "title", v_str("User Created Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the tag was created.")),
          cmap(4,
            "name", v_str("user_updated_time"),
            "title", v_str("User Updated Time"),
            "type", v_str("`$INTEGER`"),
            "short", v_str("When the tag was last updated."))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("tag"),
        "op", cmap(5,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/tags"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("tags"))),
                "parts", clist(1,
                  v_str("tags")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", v_map(),
                "select", v_map()))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(2,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/tags"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("tags"))),
                "parts", clist(1,
                  v_str("tags")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.items`")),
                "args", cmap(1,
                  "query", clist(4,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("order_by"),
                      "orig", v_str("order_by"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(4,
                      "name", v_str("order_dir"),
                      "orig", v_str("order_dir"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")),
                    cmap(5,
                      "name", v_str("page"),
                      "orig", v_str("page"),
                      "type", v_str("`$INTEGER`"),
                      "kind", v_str("query"),
                      "example", v_num(1)))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("field"),
                    v_str("order_by"),
                    v_str("order_dir"),
                    v_str("page")))),
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/tags/{id}/notes"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("tags")),
                  cmap(1,
                    "var", v_str("id")),
                  cmap(1,
                    "lit", v_str("notes"))),
                "parts", clist(3,
                  v_str("tags"),
                  v_str("{id}"),
                  v_str("notes")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.items`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(2,
                  "$action", v_str("note"),
                  "exist", clist(2,
                    v_str("field"),
                    v_str("id")))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/tags/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("tags")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("tags"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true))),
                  "query", clist(1,
                    cmap(4,
                      "name", v_str("field"),
                      "orig", v_str("field"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("query")))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("field"),
                    v_str("id")))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/tags/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("tags")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("tags"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id")))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "kind", v_str("http"),
                "method", v_str("PUT"),
                "orig", v_str("/tags/{id}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("tags")),
                  cmap(1,
                    "var", v_str("id"))),
                "parts", clist(2,
                  v_str("tags"),
                  v_str("{id}")),
                "rename", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "type", v_str("`$STRING`"),
                      "kind", v_str("param"),
                      "reqd", v_bool(true)))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
